[package]
name = "x0_contracts"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.10.2" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0-beta.0" }
starknet = "2.3.1"

[[target.starknet-contract]]
casm = true
SNErc20 = { path = "src/lib" }
# foo = { path = "vendor/foo" }

[tool.sncast]
account = "test_user_0"
accounts-file = "accounts.json"
# url = "http://127.0.0.1:5050/rpc"
url = "https://starknet-goerli.g.alchemy.com/v2/66iTEsBmPgN2fNIeNLf90oTg------"
